.zuul.yaml
Since watcher-operator is currently standalone operator. So we are only building watcher-operator and skipping meta operator build.
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/2529
Depends-On: https://github.com/openstack-k8s-operators/watcher-operator/pull/2
=> Run meta content provider against watcher-operator

.github/workflows/build-watcher-operator.yaml
This is based on nova operator workflow. It will build the images once a pr gets merged.
Jira: https://issues.redhat.com/browse/OSPRH-11419
=> Add github workflow to build and push watcher operator images

.gitignore, Makefile, README.md, ci/olm.sh
This pr adds two targets:
* `make watcher`: It generates olm.yaml file and installs the
watcher-operator using oc.
* `make watcher_cleanup`: It generates the olm.yaml file and undeploy
the watcher-operator using oc.
It also provides $CATALOG_IMAGE var to pass custom watcher-operator index image.
Jira: https://issues.redhat.com/browse/OSPRH-11419
=> Add watcher target to deploy operator via olm

config/manager/manager.yaml, config/prometheus/monitor.yaml, config/rbac/auth_proxy_service.yaml
In all the openstack-operators, openstack.org/operator-name label is used. The same needs to be used in watcher-operator. Otherwise During log collection, ci-framework env_op_images role fails while querying all controller manager pods.
This pr adds openstack.org/operator-name: watcher label to the operator.
=> Fix controller manager label

.zuul.yaml, ci/playbooks/deploy_watcher_service.yaml
This pr:
- Adds watcher-operator-base job from
podified-multinode-edpm-deployment-crc-2comp parent. This job will
deploy 2 node EDPM deployment and then deploy watcher operator using
make targets from watcher-operator repo.
- It adds hook to deploy watcher service via ci-framework hook.
Test Results: https://github.com/openstack-k8s-operators/watcher-operator/pull/9#issuecomment-2499701046 
Depends-On: https://github.com/openstack-k8s-operators/watcher-operator/pull/11
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/2569
=> Zuul job to validate watcher deployment

.github/workflows/build-watcher-operator.yaml, .github/workflows/noop.yml
Currently Devs are receiving github action workflow run email on each push on their forked repos. It is quite annoying.
Based on https://github.com/orgs/community/discussions/26704, We can disable the workflow manually or add specific condition to run workflow on forked repo.
It got skipped on my forked repo. 
Depends-On: https://github.com/openstack-k8s-operators/watcher-operator/pull/21
=> Disable workflow on forked repos

config/rbac/role.yaml, controllers/watcher_controller.go
While trying to run kuttl tests in [1], we get an error [2]
stating that the watcher controller does not have access to secrets.
This change adds the required kubebuilder annotations for secrets in the
watcher controller. Similarly, we are also missing access to services
[3].
[1] https://github.com/openstack-k8s-operators/watcher-operator/pull/14
[2] https://logserver.rdoproject.org/14/14/693d9a4c2c6b2630ef004bcd34b0bf3076826174/github-check/watcher-operator-kuttl/12efc41/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/namespaces/openstack-operators/pods/watcher-operator-controller-manager-84c899877f-wjsx8/logs/manager.log
[3] https://logserver.rdoproject.org/14/14/693d9a4c2c6b2630ef004bcd34b0bf3076826174/github-check/watcher-operator-kuttl/1968261/controlle …
=> Add secret and services to controller rbac

.zuul.yaml
It will help to report status on rdoproject.org/github-check pipeline on .github dir changes.
=> Add noop zuul job

hack/crd-schema-checker.sh
NoFieldRemoval and NoNewRequiredFields need to be temporarily disabled
since we're currently building the crds as we go.
ConditionsMustHaveProperSSATags and ListsMustHaveSSATags are disabled
beacuse they affect the Conditions type defined in lib-common, so they
are not specific to watcher-operator.
=> Disable some rules for crd schema check

.zuul.yaml, ci/playbooks/deploy_watcher_service.yaml
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/2571
Depends-On: https://github.com/openstack-k8s-operators/watcher-operator/pull/19
=> Add kuttl job

.github/workflows/docs.yaml, .gitignore, .zuul.yaml, Gemfile, Makefile, docs/Makefile
This pr adds:
- Make docs to build the docs using ascii
* Install ascii doc ruby packages using bundle
* Convert README.md to main.adoc
* Use Make target to build html files
- Github action to build and publish docs on github pages.
Generated doc from Zuul Job: https://logserver.rdoproject.org/23/23/0feff09f3ebf811cca55fbdabc3c3efe51325011/github-check/watcher-operator-doc-preview/e7e85aa/docs_build/docs_build/watcher-operator/
=> Make targets and github workflow for publishing docs

api/bases/watcher.openstack.org_watcherapis.yaml, api/v1beta1/common_types.go, api/v1beta1/watcherapi_types.go, config/crd/bases/watcher.openstack.org_watcherapis.yaml, config/samples/watcher_v1beta1_watcherapi.yaml, controllers/watcherapi_controller.go, tests/functional/watcherapi_controller_test.go, tests/kuttl/test-suites/default/watcher-api/01-cleanup-watcherapi.yaml, tests/kuttl/test-suites/default/watcher-api/03-assert.yaml, tests/kuttl/test-suites/default/watcher-api/03-deploy-watcher-api.yaml
Following the review on PR 13, there were a few changes suggested. This
PR does 2 of them:
1. Make the Secret field on the Spec required, and remove the default
from WatcherAPI. This means that the field is no longer shared
between the Watcher and WatcherAPI kinds.
2. Add more functional tests to test scenarios where the secret or
database are not present.
Related: [OSPRH-11483](https://issues.redhat.com//browse/OSPRH-11483)
=> Follow-up changes for WatcherAPI from PR 13

api/bases/watcher.openstack.org_watcherapis.yaml, api/v1beta1/common_types.go, config/crd/bases/watcher.openstack.org_watcherapis.yaml, config/samples/watcher_v1beta1_watcherapi.yaml, controllers/watcher_common.go, controllers/watcher_controller.go, controllers/watcherapi_controller.go, tests/functional/watcher_controller_test.go, tests/functional/watcherapi_controller_test.go, tests/kuttl/test-suites/default/watcher-api/03-assert.yaml, tests/kuttl/test-suites/default/watcher-api/03-deploy-watcher-api.yaml, tests/kuttl/test-suites/default/watcher/01-assert.yaml, tests/kuttl/test-suites/default/watcher/04-assert.yaml, tests/kuttl/test-suites/default/watcher/05-errors.yaml
Create an internal secret in the watcher controller to pass to the
sub CRs (atm only for WatcherAPI). Initially, this secret contains the
service password and the transport url. Eventually, this secret will be
set as the Secret field in the sub CRs specs, once they are created from
the Watcher controller.
Related: [OSPRH-11483](https://issues.redhat.com//browse/OSPRH-11483)
=> Create internal secret to consume in sub-crs

.github/workflows/docs.yaml
Build Docs github action is broken with following error[1]
```
Error: The current runner (ubuntu-24.04-x64) was detected as self-hosted because the platform does not match a GitHub-hosted runner image (or that image is deprecated and no longer supported).
```
Using ruby/setup-ruby@v1 fixes the issue.
Similar fix is proposed here also https://github.com/openstack-k8s-operators/data-plane-adoption/pull/777
Link:
[1]. https://github.com/openstack-k8s-operators/watcher-operator/actions/runs/12664082918/job/35291667930
=> Update Ruby action

.github/workflows/build-watcher-operator.yaml, .github/workflows/sync-to-fr1-branch.yaml
In order to align with the resto of operators we need to have a 18.0-fr1 branch. However, we do not want to manually cherry-pick every commit but to get any new commit into the branch until we have a fully functional repo.
This patch is adding a job which will sync content from main to the branch 18.0-fr1 after any merge into the main branch.
We may need to first create the new branch manually.
=> Add a github action to sync content from main to fr1 branch

api/v1beta1/common_types.go, api/v1beta1/watcher_webhook.go, api/v1beta1/zz_generated.deepcopy.go, controllers/watcher_controller.go, tests/functional/watcher_controller_test.go
databaseInstance and rabbitMqClusterName are required fields. If an user specify databaseInstance and rabbitMqClusterName field as empty string. The webhook should fail it saying as there cannot be empty.
This pr adds the validations for the same.
Jira: https://issues.redhat.com/browse/OSPRH-11933
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/2658
=> Add webhook validation for empty database and rabbitmq

Makefile, api/v1beta1/common_types.go, config/default/manager_default_images.yaml, config/samples/watcher_v1beta1_watcherapi.yaml, tests/kuttl/test-suites/default/common/deploy-with-defaults.yaml, tests/kuttl/test-suites/default/watcher/04-deploy-with-precreated-account.yaml
Currently watcher-operator defaults to antelope release container images. However, in order to integrate in openatck-k8s-operators environments it requires integration with prometheus which will only be supported in master (epoxy) cycle.
This patch is setting master container images as defaults. Once epoxy is release we can move to them if available.
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/2658
=> Default watcher container images to master release

pkg/watcherapi/deployment.go, tests/functional/watcher_test_data.go, tests/kuttl/test-suites/default/watcher/01-assert.yaml, tests/kuttl/test-suites/default/watcher/04-assert.yaml, tests/kuttl/test-suites/default/watcher/05-errors.yaml
Remove the '-api' suffix from the deployment name, as it usually is
redundant.
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/2658
=> Rename the watcherapi deployment

.zuul.yaml
Thanks to watcher api service and tls integration, we are now able to run watcher_tempest_plugin.tests.api.admin.test_api_discovery.TestApiDiscovery[1] test in EDPM CI.
It will act as a base for keep existing watcher integration healthy.
Links:
[1]. https://github.com/openstack-k8s-operators/watcher-operator/pull/47#issuecomment-2607474033
Related-Jira: https://issues.redhat.com/browse/OSPRH-11948
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/2675
=> Run minimal watcher tempest api test

.zuul.yaml, ci/playbooks/deploy_cluster_observability_operator.yaml
In order to test integration with watcher and prometheus datasource, we need to install telemetry on the controlplane.
This pr adds the kustomization for enabling telemetry service.
Related-Jira: https://issues.redhat.com/browse/OSPRH-11948
=> Deploy telemetry service on controlplane

api/bases/watcher.openstack.org_watcherapis.yaml, api/bases/watcher.openstack.org_watchers.yaml, api/v1beta1/common_types.go, config/crd/bases/watcher.openstack.org_watcherapis.yaml, config/crd/bases/watcher.openstack.org_watchers.yaml, controllers/watcher_controller.go, controllers/watcherapi_controller.go, pkg/watcher/constants.go, templates/watcher/config/watcher-api-config.json, tests/functional/base_test.go, tests/functional/watcher_controller_test.go, tests/functional/watcherapi_controller_test.go, tests/kuttl/test-suites/default/watcher/04-assert.yaml, tests/kuttl/test-suites/default/watcher/04-deploy-with-precreated-account.yaml
This patch adds support for services config customization:
- A top level `customServiceConfig` in Watcher CR is used for configuration snippets that are desired in all the Watcher services.
- A second level `customServiceConfig` in each one of the templates, as APIServiceTemplate, etc.. defines per-service specific config.
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/2658
=> Add CustomServiceConfig

templates/watcher/config/10-watcher-wsgi-main.conf, templates/watcher/config/httpd.conf, templates/watcher/config/ssl.conf, templates/watcher/config/watcher-api-config.json
Introduce several fixes for watcher config:
- **Remove default watcher conf file from rpm**
- **Add ssl.conf file to watcher config**
- **Direct all apache logs to stdout**
=> Various fixes for watcher config

templates/watcher/config/00-default.conf
The new datasource is merged in the master branch of watcher repo [1] and ceilometer has been removed [2], so we need to switch to the prometheus datasource:
[1] https://review.opendev.org/c/openstack/watcher/+/934423
[2] https://review.opendev.org/c/openstack/watcher/+/937625
=> Switch datasource to prometheus

api/bases/watcher.openstack.org_watcherdecisionengines.yaml, api/v1beta1/watcherdecisionengine_types.go, config/crd/bases/watcher.openstack.org_watcherdecisionengines.yaml, config/samples/watcher_v1beta1_watcherdecisionengine.yaml, controllers/watcher_common.go, controllers/watcherdecisionengine_controller.go, pkg/watcherdecisionengine/statefulset.go, templates/watcher/config/watcher-decision-engine-config.json, templates/watcherdecisionengine, tests/functional/sample_test.go, tests/functional/watcher_test_data.go, tests/functional/watcherapplier_controller_test.go, tests/functional/watcherdecisionengine_controller_test.go, tests/kuttl/test-suites/default/common/cleanup-errors.yaml, tests/kuttl/test-suites/default/watcher-decision-engine/01-cleanup-watcherdecisionengine.yaml, tests/kuttl/test-suites/default/watcher-decision-engine/03-assert-default.yaml, tests/kuttl/test-suites/default/watcher-decision-engine/03-deploy-decision-engine.yaml
Adds config and deploys StatefulSet for WatcherDecisionEngine
This follows on from [1] to add missing configuration collection
and creation of a StatefulSet for the DecisionEngine.
[1] https://github.com/openstack-k8s-operators/watcher-operator/pull/44
Depends-On: https://github.com/openstack-k8s-operators/install_yamls/pull/1011
=> Adds config and deploys StatefulSet for WatcherDecisionEngine

.zuul.yaml, Makefile, ci/olm.sh, ci/playbooks/deploy_watcher_service.yaml
In order to test opendev watcher master content in CI job, this pr adds following things:
* opendev-master-watcher-operator-pipeline project template which will run meta content provider from master and  then Deploy EDPM job watcher-operator-validation-master from mastter content. It will help to test any opendev watcher patches with master edpm  job.
* It changes the existing job watcher-operator-validation (still deploying the antelope content) with update_containers: false to avoid using meta content provider containers. This change will help to test master content with antelope job as
in downstream, we are going to backport lots of watcher master patches downstream. It will help to avoid breakage in advance.
* It also updates the existing watcher-operator-validation and …
=> Test opendev watcher master content in CI job

ci/playbooks/deploy_watcher_service.yaml
When running a provider job that build openstack services, we may want to provide a specific tag defined in a dependent job, not from delorean or the default one.
=> Add a var to override watcher services tag

.gitignore, Makefile, README.md, docs/Makefile, docs/install_guide.adoc, docs/main.adoc
This PR adds the first of two user facing docs,
the operator install guide. A worked example will be added afterwards.
The guide takes the user through installing the operator and deploying the service once the user already has and operator-installed Openstack environment with
telemetry available.
=> Add install guide for the Watcher Operator

controllers/watcher_common.go, controllers/watcherapi_controller.go, controllers/watcherapplier_controller.go, controllers/watcherdecisionengine_controller.go, pkg/watcherapi/statefulset.go, templates/watcherapi/config/watcher-api-config.json, tests/functional/base_test.go, tests/functional/watcher_controller_test.go, tests/functional/watcher_test_data.go, tests/functional/watcherapi_controller_test.go, tests/kuttl/test-suites/default/watcher-api-scaling/01-assert.yaml, tests/kuttl/test-suites/default/watcher-api-service-override/01-assert.yaml, tests/kuttl/test-suites/default/watcher/01-assert.yaml, tests/kuttl/test-suites/default/watcher/04-assert.yaml
Introduce several changes needed to support TLS on the endpoints. This
change does:
- Use HTTPS in the api statefulset probes if TLS is used
- Ensure all controllers are watching the secrets they consume (most were missing the CA secret)
- Create volumes for TLS certificates and copy them to the API pods
- Validate TLS input in watcherapi controller
Related: https://issues.redhat.com/browse/OSPRH-13020
=> Introduce some changes to prepare for TLS support

.zuul.yaml, Makefile, ci/playbooks/deploy_watcher_service.yaml, ci/watcher_v1beta1_watcher.yaml
We have decision-engine and applier integrated in the Watcher controller so we can increase tempest coverage. I am excluding some tests from the watcher plugin:
- client_functional tests require watcherclient installed in the tempest  container.
- strategies execute tests are failing with an error while accessing resource traits for compute nodes. Until we can manage this, we can exclude these tests.
Also this patch is setting some tempest parameters aligned with upstream     ones and forcing to use the watcher-tempest-pluging from upstream master branch source instead of rpm.
Resolves: https://issues.redhat.com/browse/OSPRH-12114
=> Enable watcher_tempest_plugin tests in validation jobs

ci/olm.sh, ci/playbooks/deploy_cluster_observability_operator.yaml
For some reason, we are using `development` channel which is not longer found in the redhat catalog for COO.
=> Use stable channel for COO installation

renovate.json
renovate is used to manage our depnecies in a corrdinated way
across all the operators
this change enables renovate for the watcher operator
=> add renovate confiugration

docs/install_guide.adoc
The tls section was moved into the 'apiServiceTemplate' in the CRD, we
need to update it in the CR included in the doc.
=> Fix the tls section in the install_guide doc

Gemfile
the REXML modle was previously pinned to a verion with several
know cves related to regex perforamce.
this change removes the cap and set 3.3.9 as our new minium
requirement as that is the first release with no known vulnerablities
=> unpin REXML documemtion dependency

Makefile, ci/playbooks/deploy_watcher_service.yaml
The correct vars passed to make watcher are as follow[1]: WATCHER_API_IMAGE,  WATCHER_DECISION_ENGINE_IMAGE and WATCHER_APPLIER_IMAGE. We need to use the same var in deploy_watcher_service hook.
=> Fix the image name in deploy_watcher_service hook

.zuul.yaml
Instead of running at the end of the infra playbook, run it just before
running the tests. This means the watcher operator will be installed
after the openstack-operator is, which will prevent the watcher operator
crashing and having to restart until the openstack-operator is
available.
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/2735
=> Run watcher hook at the beginning of kuttl tests

.zuul.yaml, ci/watcher_v1beta1_watcher_tlse.yaml
Change one of the validation jobs to deploy watcher with TLSe. For now,
this means we also need to create certificates and set the right
secrets in the Watcher CR.
Depends-On: https://github.com/openstack-k8s-operators/watcher-operator/pull/57
=> Deploy Watcher with TLS in one of the validation jobs

ci/playbooks/deploy_watcher_service.yaml
Using the watcher_repo var in the CI playbooks allows for overrides when required.
=> Use a watcher_repo var to allow for overrides

.zuul.yaml, ci/playbooks/deploy_watcher_service.yaml
Move the dependencies and some job variables from watcher-operator-base
into an intermediate base job. This allows to use the base job without the
content provider job, for example in the master pipeline. Also add a new
parameter to set the registry url without using the content provider
vars.
=> Move job dependencies from watcher-operator-base

.zuul.yaml, ci/scenarios/edpm.yml, ci/scenarios/kuttl.yml, ci/tests/watcher-master.yml
Our jobs are getting bigger, and new jobs are duplicating some common information, while other may have different test configuration per upstream branch
This patch tries to better organize configuration in scenario and test files that can be shared between jobs.
=> Refactor jobs to use scenario and test config files

.zuul.yaml
Currently openstack-experimental pipeline used to run EDPM jobs on watcher opendev repos. But we want to run openstack-check pipeline on each watcher prs in order to make sure it does not break EDPM jobs.
This pr updates the pipeline to openstack-check. It will provide feedback on each patches via rdo third party check job.
=> Use openstack-check pipeline to run EDPM job on watcher opendev repos

.zuul.yaml
Since watcher-operator uses master and not antelope container, create
a job to run in the master pipeline to ensure new content does not break
watcher.
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/2783
=> Add job for testing watcher in the master pipeline

config/manifests/bases/watcher-operator.clusterserviceversion.yaml
We need to be available in the WebUI to be installed standalone.
Closes: https://issues.redhat.com/browse/OSPRH-14724
=> Remove non-standalone operatory-type for watcher-operator

docs/install_guide.adoc, docs/user_workflow.adoc
This PR fixes the install guide to remove the watcher service showing as available before installation.
It also remove a link that is no longer available.
=> Remove prometheus graphic & update service result

.zuul.yaml, ci/tests/watcher-master.yml
This pr fixes following things:
- Use watcher catalog image from cifmw_operator_build_output var provided by meta content provider.
- Use proper tempest images when depends on from opendev is used and release is master or antelope.
Test results related to proper tempest image when opendev depends-on is used: https://github.com/openstack-k8s-operators/ci-framework/pull/2759#issuecomment-2735341642
=> Improvements to zuul job related to operator image and tempest

.zuul.yaml
enable testing with 4.18 and 4.16
=> Add OCP 4.16 job when switching NS to OCP 4.18

.zuul.yaml
This is failed due to no having the right merge-mode [1] set.
https://softwarefactory-project.io/zuul/t/rdoproject.org/config-errors?project=openstack-k8s-operators%2Fwatcher-operator&skip=0
[1] https://zuul-ci.org/docs/zuul/latest/config/project.html#attr-project.merge-mode
=> Set merge-mode for project openstack-k8s-operators/watcher-operator

.zuul.yaml
This change removes the description field from project/project-template. This is not a valid field, check the documentation [1].
[1] - https://zuul-ci.org/docs/zuul/latest/config/project.html#project-template
=> Remove description field from project-template

.zuul.yaml
In order to run rdo third party jobs in openstack-check pipeline to test opendev watcher projects gerrit review with meta content provider and EDPM job with/without operator pull request depends-on,
We need to add override-checkout and required-projects at project-template pipeline level. We also need to use Zuul Pragma feature to alter Zuul configuration for this project and load both master opendev watcher branch and main watcher-operator branch to complete the zuul job graph and run the job.
Note: It also removes override-checkout from zuul job definition as it is no longer needed.
=> Add override-checkout and required-projects at project-template pipeline level

controllers/watcherapi_controller.go, controllers/watcherapplier_controller.go, controllers/watcherdecisionengine_controller.go
while seting up my editor to highlight go
i found a could of nill pointer derefs via static checking
i have not reviewed all file but this commit fixes the 3 cases
that i found today.
=> fix nil point deref in error path.

.zuul.yaml
It will help to run openstack-check pipeline jobs on opendev master branch only.
=> Run openstack-check pipeline jobs on master branch only.

config/manifests/bases/watcher-operator.clusterserviceversion.yaml
Currently, OLM suggests to install the operator in `openstack` while it should be installed in `openstack-operators`.
This patch is setting operatorframework.io/suggested-namespace [1] to `openstack-operators` as the openstack operator does [2].
Resolves: https://issues.redhat.com/browse/OSPRH-15432
[1] https://docs.redhat.com/en/documentation/openshift_container_platform/4.16/html/operators/developing-operators#osdk-csv-manual-annotations-deprecated_osdk-generating-csvs
[2] https://github.com/openstack-k8s-operators/openstack-operator/blob/d648626207ce2cbfebe219a01456f4f87b2abc4d/config/manifests/bases/openstack-operator.clusterserviceversion.yaml#L14
=> Suggest to install watcher-operator in openstack-operators

ci/tests/watcher-master.yml
Until we refine the configuration of real and injected data in the same job, let's skip real data ones.
Required for https://review.opendev.org/c/openstack/watcher-tempest-plugin/+/940171
=> Skip real_data tests from watcher tempest plugin

.zuul.yaml, ci/files/containers.yaml, ci/playbooks/copy_container_files.yaml
This pr adds:
- tcib containers config file to build watcher and tempest all container
- opendev-epoxy-watcher-operator-pipeline project template to run in
github-check.
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/2940
Depends-On: https://github.com/openstack-k8s-operators/repo-setup/pull/33
Jira: [OSPRH-16312](https://issues.redhat.com//browse/OSPRH-16312)
=> Add epoxy related jobs and project template 

.zuul.yaml
openstack-check jobs runs content provider and edpm jobs. It does not have any relationship with .zuul.yaml. So skip running openstack-check pipeline on these changes to avoid wasting resources.
=> Skip openstack-check jobs on opendev watcher .zuul.yaml changes

.zuul.yaml
master branch is not longer supported in centos9 (python3.9) upstream, so we should avoid using it specially in a stable job with antelope based controlplane.
This patch is replacing the jobs using watcher from master in antelope controlplane jobs by epoxy based watcher containers. The resulting testing combination is:
1. Antelope controlplane + epoxy watcher (centos 9)
- Job on ocp 4.18
- Job on ocp 4.16
2. Master controlplane + master watcher (centos 9)
- Job on ocp 4.18
Note we will need to migrate [2] to centos10 which is work in progress right now.
=> Replace antelope-controlplane + master-watcher jobs by antelope + epoxy

templates/00-default.conf
In HA tests it was identified that pymemcache backend does not recover/fail over to the next memcache instance when one goes away unexpected. Using memcache_pool with bmemcache does failover properly.
The memcache_sasl_enable=true is a workaround to force oslo.cache to switch to the bmemcache driver, which is the only driver in memcache_pool supporting tls+fips.
Jira: [OSPRH-16651](https://issues.redhat.com//browse/OSPRH-16651)
Co-outhored-by: Luca Miccini <lmiccini@redhat.com>
=> Change memcache to use memcache_pool driver

.zuul.yaml, ci/files/containers.yaml, ci/playbooks/copy_container_files.yaml
master branch is not longer supported in centos9 (python3.9) upstream, so we should avoid using it specially in a stable job with antelope based controlplane.
This patch is replacing the jobs using watcher from master in antelope controlplane jobs by epoxy based watcher containers. The resulting testing combination is:
1. Antelope controlplane + epoxy watcher (centos 9)
- Job on ocp 4.18
- Job on ocp 4.16
2. Master controlplane + master watcher (centos 9)
- Job on ocp 4.18
Note we will need to migrate [2] to centos10 which is work in progress right now.
This is a slightly modified backport of https://github.com/openstack-k8s-operators/watcher-operator/pull/165/
Also includes backport of https://github.com/openstack-k8s-operators/watcher-operator/pull/152
=> [18.0-fr2] Replace antelope-controlplane + master-watcher jobs by antelope + epoxy

.zuul.yaml
With https://github.com/openstack-k8s-operators/watcher-operator/pull/159#issuecomment-2888916218, CS10 EDPM POC job is now working with tls.
https://review.rdoproject.org/r/c/rdo-jobs/+/57650 pushes containers with current tag in master integration line.
Let's reuse this line to test cs10 master current containers.
Depends-On: https://github.com/openstack-k8s-operators/openstack-operator/pull/1443
Resolves: https://issues.redhat.com//browse/OSPRH-16721
=> Repurpose periodic watcher validation job to test cs10 master containers

templates/00-default.conf
Since https://review.opendev.org/c/openstack/oslo.cache/+/949978 is merged and backported to all the stable releases let's remove the workaround.
Patch was also cherry-picked to downstream antelope.
Jira: https://issues.redhat.com/browse/OSPRH-17029
=> Remove memcached_sasl_enabled=True workaround

.zuul.yaml
Lately, we have been hitting resources issues in validation jobs running on 4.16 specially.
nova-operator is using 3xl size for crc in their jobs [1] and no resource issues are found in their logs, so I am proposing to update the crc node size to 3xl.
For 4.18 jobs we are inheriting the nodesets definition and seems more stable so I'm keeping them as-is so far.
[1] https://github.com/openstack-k8s-operators/nova-operator/blob/c71791ea3caa04b04445c59f935a335848f38861/.zuul.yaml#L60
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/3012
=> Update crc nodes to 3xl in 4.16 jobs

.zuul.yaml
In periodic job, we test current tagged containers. Currently watcher-db-sync pod is hitting ImagepUlloff error due to current-podified usage.
The correct tag is current. Let's use watcher_services_tag to pass the correct tag.
=> Pass watcher_services_tag: current to periodic job

controllers/watcher_controller.go, controllers/watcherapi_controller.go, controllers/watcherapplier_controller.go, controllers/watcherdecisionengine_controller.go
Currently we use deferred call to always update the status field when Reconcile call exits, which seems correct for any other error except Reconciler exits due to panic.
This change adds a call to recover function and try to handle panic and log error.
Closes: [OSPRH-17017](https://issues.redhat.com//browse/OSPRH-17017)
=> Do not update status when reconciler exits due to panic

ci/scenarios/edpm.yml
When we run make watcher_deploy on controller in uni jobs. It fails with 'make: go: No such file or directory'.
go was not installed on the controller leading to watcher service deploy failure.
Running make download_tools install golang and fixes the issue.
Signed-off-by: Chandan Kumar (raukadah) <raukadah@gmail.com>
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/3063
Jira: [OSPRH-12132](https://issues.redhat.com//browse/OSPRH-12132)
=> Install golang on controller before deploying watcher

.zuul.yaml, Makefile, ci/ctlplane_watcher_patch.yaml, ci/full_watcher_v1beta1_watcher_tlse.yaml, ci/playbooks/deploy_watcher_service.yaml, ci/scenarios/kuttl.yml, hack/stop_integrated_watcher.sh
We are working in integrating the watcher-operator in the openstack-operator following the same approach that other openstack services operators are doing.
To make the transition smooth, I am proposing to make the jobs compatible with both standalone and integrated mode by implementing following changes:
- Now, the content provider jobs should be rebuilding the watcher-operator and the openstack-operator. For the integration mode, that should make that, when the openstack-operator deployes the watcher-operator it will run using the patched version of it.
- I'm adding logic to find out if the watcher-operator is already deployed when running the deploy_watcher_service.yaml playbook. If the Watcher CRDs are already installed, it means the watcher operator has been installed by the …
=> Make deployment jobs compatible with standalone and integrated mode

ci/files/configure_telemetry_for_watcher_service.yaml, ci/files/remove-monitoring-stack-field.yaml, ci/playbooks/deploy_watcher_service.yaml, ci/scenarios/edpm.yml
In uni03gamma job, telemetry is enabled but remotewritereceiver is not enabled. It is needed by watcher tempest plugin to push metrics using promtool over prometheus. This pr adds the patch file to enable remotewritereceiver on the controlplane.
It also drops cifmw_edpm_prepare_kustomizations file as we moved the required config to enable telemetry in deploy_watcher_service playbook.
Assisted-By: Gemini 2.5 Flash
(cherry picked from commit 57a1181204ef3d3920d69ec1e88bf2a8cb081bf6)
=> [18.0-fr3]Enable telemetry with remotewritereceiver

.zuul.yaml
This job no longer runs in our pipeline. It is good to drop this job.
=> Drop watcher-operator-validation job

.zuul.yaml, ci/playbooks/copy_container_files.yaml
It will help to reuse the path so that other project run the meta content provider as it is.
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/3096
=> Use zuul_project_path var to define project path in copy containers

.zuul.yaml
Depends-On: https://github.com/openstack-k8s-operators/watcher-operator/pull/202
=> Use current-tested in cs10 master watcher validation job

.zuul.yaml
Jobs with injected data are failing when we have metrics mixed from real exporters and injected ones.
This patch is adding a parameter to specify the list of enabled exporters which is provided by edpm_ansible [1] and configured via ci-framework [2].
This should fix the master job.
[1] https://github.com/openstack-k8s-operators/edpm-ansible/blob/fa813b904c6e70a28f0b86865fc190ccd2282ba6/roles/edpm_telemetry/defaults/main.yml#L56-L60
[2] https://github.com/openstack-k8s-operators/ci-framework/pull/3090/
Depends-On: https://review.opendev.org/c/openstack/watcher-tempest-plugin/+/953416
Depends-On: https://github.com/openstack-k8s-operators/watcher-operator/pull/202
=> Disable ceilometer_agent_compute and node_exporter in injected data jobs

.zuul.yaml
Jobs with injected data are failing when we have metrics mixed from real exporters and injected ones.
This patch is adding a parameter to specify the list of enabled exporters which is provided by edpm_ansible [1] and configured via ci-framework [2].
[1] https://github.com/openstack-k8s-operators/edpm-ansible/blob/fa813b904c6e70a28f0b86865fc190ccd2282ba6/roles/edpm_telemetry/defaults/main.yml#L56-L60
[2] https://github.com/openstack-k8s-operators/ci-framework/pull/3090/
=> [18.0-fr3] Disable ceilometer_agent_compute and node_exporter in injected data jobs

ci/playbooks/deploy_watcher_service.yaml
We need to delete injected metrics between tests to avoid overlapping between tests
This can be done by enabling this API and executing requests like [1]
There is no option (by now) to do it on the openstackcontrolplane object, so now we have to patch prometheus after it is created, we will manage to add an option to include this API on the controlplane object [2]
[1] https://metric-storage-prometheus.openstack.svc:9090/api/v1/admin/tsdb/delete_series?match[]={job="promtool"}
[2] https://github.com/rhobs/observability-operator/blob/d0e25a27bde3ba2ca6c39a6fb259e93c8ae8cc99/pkg/apis/monitoring/v1alpha1/types.go#L177
=> Enable prometheus admin API to allow us to delete old injected metrics

ci/playbooks/deploy_watcher_service.yaml
Change how the watcher hook waits for the new prometheus-metric-storage
container after patching the metrie-storage service to enable admin api.
In some runs [1] the current method of waiting was calling oc wait in
between the time where openshift would delete the old container and
creating the new one, thus not waiting the specified timeout.
[1] https://softwarefactory-project.io/zuul/t/rdoproject.org/build/e058ff4467134a258e283c9da17e0192
=> Change how the watcher hook waits for prometheus

.zuul.yaml, ci/tests/watcher-tempest.yml
A new upstream patch is adding microversion testing for watcher-tempest-plugin, and it will be mandatory to configure the min and max microversion to be tested in each job. To make the opendev job to work with new microversions, we can set max_microversion to 'latest' and for stable branches jobs we override with the latest microversion for each release. This PR also sets 1.4 as max microversion for Epoxy. It also renames the test configuration file to replaces the suffix master since this file is being used in all jobs.
Depends-On: https://review.opendev.org/c/openstack/watcher-tempest-plugin/+/956306
=> Configure min and max microversion for watcher-tempest-plugin

.zuul.yaml, ci/tests/watcher-tempest.yml
Currently, watcher-tempest-plugin is pinned in RDO to tag 3.4.0 [1].
Some fixes and improvements have been merged since then and the required backports in the watcher epoxy branch are merged, so let's bump the tempest plugin.
Given that in the past it has been usual that patches in master branch of the plugin requires backports in the watcher epoxy branch, I am not proposing to follow the master branch of the plugin but using a known good commit.
[1] https://github.com/redhat-openstack/rdoinfo/blob/ee923461f857154321314796ed06c8365c1457d0/tags/epoxy.yml#L943-L946
=> Bump watcher-tempest-plugin for epoxy jobs to known good commit

.zuul.yaml
Before moving to role, when the 99-logs.yml playbook was executed, the
variables was not set to, so it pick default value which is false, so
the playbook was executed. Now when it is in `cifmw_setup` role in
`run_logs.yml` task file, the condition is possitive, so it is skipped.
Add 'zuul_log_collection' var to overwrite other existing vars and
trigger gather facts.
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/3208
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/3231
=> Set zuul_log_collection to false to trigger must-gather facts

config/manifests/bases/watcher-operator.clusterserviceversion.yaml
This annotation is technically optional, but it's needed for downstream productization[1]:
> Free-form array for listing any specific subscriptions that are
> required to use the Operator
Adding it here simplifies downstream CSV post-processing.
[RELDEL-7851](https://issues.redhat.com//browse/RELDEL-7851)
[1] https://docs.okd.io/4.18/operators/operator_sdk/osdk-generating-csvs.html#osdk-csv-annotations-other_osdk-generating-csvs
=> Add valid-subscription annotation to CSV

config/manifests/bases/watcher-operator.clusterserviceversion.yaml
Manual cherry-pick from https://github.com/openstack-k8s-operators/watcher-operator/pull/257
This annotation is technically optional, but it's needed for downstream productization[1]:
> Free-form array for listing any specific subscriptions that are
> required to use the Operator
Adding it here simplifies downstream CSV post-processing.
[RELDEL-7851](https://issues.redhat.com//browse/RELDEL-7851)
[1] https://docs.okd.io/4.18/operators/operator_sdk/osdk-generating-csvs.html#osdk-csv-annotations-other_osdk-generating-csvs
(cherry picked from commit cf65968beff26a3e355d53bf18f9be9c8a580fdc)
=> [18.0-fr3] Add valid-subscription annotation to CSV

.zuul.yaml, ci/scenarios/edpm-no-notifications.yml, ci/scenarios/edpm.yml
This PR adds the posibility of using different edpm scenarios to add watcher to kustomize object but using different scenarios depending on the configuration of watcher that we want to use
nova-notifications usage is added to default scenario (edpm), but not on epoxy jobs (edpm-no-notifications), where it is also decreased the model obtain process to 60 seconds.
Nodeset is also modified on default job, required because adding the new rabbitmq queue for nova-notifications
Results of the last CI Run:
Master: https://logserver.rdoproject.org/2a3/rdoproject.org/2a3fd1dd32cf4a1e94bab0a38d4ff9e5/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/namespaces/openstack/crs/watchers.watcher.openstack.org/watcher.yaml
Epoxy: …
=> Modify edpm scenarios to install with and without nova-notifications

.zuul.yaml, tests/kuttl/test-suites/default/watcher-api-scaling/01-assert.yaml, tests/kuttl/test-suites/default/watcher-api-scaling/01-deploy-with-defaults.yaml, tests/kuttl/test-suites/default/watcher-notification/01-assert.yaml, tests/kuttl/test-suites/default/watcher-tls-certs-change/01-assert.yaml, tests/kuttl/test-suites/default/watcher-tls/01-assert.yaml, tests/kuttl/test-suites/default/watcher-tls/03-assert.yaml, tests/kuttl/test-suites/default/watcher-tls/04-assert.yaml, tests/kuttl/test-suites/default/watcher-tls/05-assert.yaml, tests/kuttl/test-suites/default/watcher-topology/01-assert.yaml, tests/kuttl/test-suites/default/watcher/01-assert.yaml, tests/kuttl/test-suites/default/watcher/04-assert.yaml, tests/kuttl/test-suites/default/watcher/04-deploy-with-precreated-account.yaml
Consume the watcher service container images from the content provider
job in the kuttl job.
Remove the checks for the container images in the kuttl asserts.
Fix tls field in watcher kuttl test suite
The kuttl test suite had a misplaced caBundleSecretName field. This was
not detected before because even though the pods could not communicated
properly with keystone or rabbitmq, they kept running. After switching
to containers built from watcher master, the decision engine tries to
connect to keystone and fails, crashing.
=> Use content provider service containers in kuttl

ci/tests/watcher-tempest.yml
The cifmw_tempest_tempestconf_config has been deprecated for a while, so it would be the best to start using the new alternative cifmw_test_operator_tempest_tempestconf_config. There should be no impact on the jobs, it should just let us cleanup the deprecated parameter.
=> Remove deprecated cifmw_tempest_tempestconf_config

ci/scenarios/edpm.yml
Move rabbitmq notifications queue from enabling at nova/cinder/watcher level to openstack controlplane level after that usage is available since https://github.com/openstack-k8s-operators/openstack-operator/pull/1591.
`delayStartSeconds` parameter removed from rabbitmq notifications queue creation because it is not necessary, it is automatically added by controlplane when creating a new queue
=> Move rabbitmq notifications queue to controlplane level
